
import javax.swing.JOptionPane;

/**
 * Author: Arthur Laks
 * CSIT 210 - GUI Lab
 * Overview: Allows the user to determine the pay of employees.
 * Input: The user chooses the type of employee and the hours and rate or bonus.
 * Output: Displays the pay of the employee.
 * Variables: calculateButton, employeeType, hoursLabel, hoursTextField, payLabel, rateLabel, rateTextField
 * Plan:
 * 1. Initializes the various components and adds them to the panel (that part is handled by NetBeans' form
 designer's automatically generated code.
 * 2. In the actionEvent for the button, calculates the pay based on the option selected in the employeeType
 ComboBox and the values the user entered in the two text fields.
 * 3. Displays that value in one of the labels.
 * 4. In the ActionEvent for the comboBox, resets both text fields to zero and disables them if the selected
 item is volunteer or salaried.
 * @version 1.0 2013-05-07
 */
public class PayrollPanel extends javax.swing.JPanel {

    /**
     * Creates new form Payroll
     */
    public PayrollPanel() {
        initComponents();
    }

    /**
     * Since I am inexperienced with the NetBeans form designer, I set many properties that I did not have
     * to set.
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        employeeType = new javax.swing.JComboBox();
        hoursTextField = new javax.swing.JTextField();
        hoursLabel = new javax.swing.JLabel();
        rateLabel = new javax.swing.JLabel();
        rateTextField = new javax.swing.JTextField();
        calculateButton = new javax.swing.JButton();
        displayPay = new javax.swing.JLabel();
        payLabel = new javax.swing.JLabel();

        employeeType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select an Employee Type...", "Salaried", "Hourly", "Volunteer" }));
        employeeType.setSelectedItem("Select an Employee Type...");
        employeeType.setName("employeeType"); // NOI18N
        employeeType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OnChange(evt);
            }
        });

        hoursTextField.setName("hoursWorked"); // NOI18N

        hoursLabel.setText("Hours:");
        hoursLabel.setToolTipText("The number of hours the employee worked");
        hoursLabel.setName("hoursLabel"); // NOI18N

        rateLabel.setText("Rate:");
        rateLabel.setToolTipText("The ratio of hours to pay.");
        rateLabel.setName("rateLabel"); // NOI18N

        rateTextField.setToolTipText("");
        rateTextField.setName("rateTextField"); // NOI18N

        calculateButton.setMnemonic('C');
        calculateButton.setText("Calculate Pay");
        calculateButton.setToolTipText("");
        calculateButton.setName("calculatePay"); // NOI18N
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        displayPay.setText("$0.00");
        displayPay.setToolTipText("");
        displayPay.setName("displayPay"); // NOI18N

        payLabel.setText("Pay:");
        payLabel.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(calculateButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(employeeType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hoursLabel)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(hoursTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(payLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(displayPay)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(employeeType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hoursLabel)
                    .addComponent(hoursTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rateLabel)
                    .addComponent(rateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculateButton)
                    .addComponent(displayPay)
                    .addComponent(payLabel))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        rateLabel.getAccessibleContext().setAccessibleName("Rate: ");
    }// </editor-fold>//GEN-END:initComponents
/**
 * This method is called by the anonymous actionListener class of in the initComponents method that 
subscribes to the button's click event.  
 */
    private void onClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onClick
        java.text.NumberFormat formatter=java.text.NumberFormat.getCurrencyInstance();
        switch(employeeType.getSelectedItem().toString()){
            case "Salaried":
                double bonus=Double.parseDouble(JOptionPane.showInputDialog("What is the bonus?")
                        .replace('$',(char)0)); //If the user enters the bonus preceded by a dollay sign,
                //String.replace will replace it with null (which is at 0 in the unicode table) so that
                //Double.parseDouble will not throw an exception
                displayPay.setText(formatter.format(2000+bonus));
                break;
            case "Hourly":
                Double pay=Integer.parseInt(hoursTextField.getText())*Double.parseDouble(rateTextField.getText());
                displayPay.setText(formatter.format(pay));
                break;
            case "Volunteer":
                displayPay.setText("$0.00");
                break;
            case "Select an Employee Type...":
                JOptionPane.showMessageDialog(null, "Please select an employee type.",
                        "Payroll",JOptionPane.ERROR_MESSAGE);
                break;
        }

    }//GEN-LAST:event_onClick
    /**
    * This method is called by the anonymous actionListener class of in the initComponents method that 
subscribes to the ComboBox's click event.
    */
    private void OnChange(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OnChange
        hoursTextField.setText("0");    
        rateTextField.setText("0.0");
        String selectedItem=employeeType.getSelectedItem().toString();
        if(selectedItem.equals("Salaried")||selectedItem.equals("Volunteer")){
            hoursTextField.setEnabled(false);
            rateTextField.setEnabled(false);
        }else{
            hoursTextField.setEnabled(true);
            rateTextField.setEnabled(true);
        }
            
    }//GEN-LAST:event_OnChange

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculateButton;
    private javax.swing.JLabel displayPay;
    private javax.swing.JComboBox employeeType;
    private javax.swing.JLabel hoursLabel;
    private javax.swing.JTextField hoursTextField;
    private javax.swing.JLabel payLabel;
    private javax.swing.JLabel rateLabel;
    private javax.swing.JTextField rateTextField;
    // End of variables declaration//GEN-END:variables
}
